### ISSUE TITLE
如何实现同路由url多页签？

### ISSUE THREAD

**Issue by zztss** [izhaorui/Zr.Admin.NET#17]
例如有个用户列表，点击一行编辑后，
打开一个 system/user?id=1 
再点击另一行
打开 system/user?id=2 
目前的路由和el-tabs是深度绑定的，因此同时只能存在一个
我甚至想打开第一个页签时，页签标题是 用户编辑-1，页签标题是 用户编辑-2

**Comment by izhaorui** [comment]
https://www.izhaorui.cn/doc/frontend/#tab-%E5%AF%B9%E8%B1%A1

**Comment by izhaorui** [comment]
没看到其他vue项目有这样的功能

**Comment by zztss** [comment]
> Reference in n

确实比较少，研究了半天算了，准备关闭tagview功能，不然用户会需要这个功能
